### ISSUE TITLE
Sort of array isn't right.

### ISSUE THREAD

**Issue by rustyconover** [rafipiccolo/arraystat#1]
Hi, 

You use of Array.sort() isn't quite right.

Right now you're doing:

```
> [1, 2, 3, 10, 9].sort()
[ 1, 10, 2, 3, 9 ]
```

But sort is returning the elements sorted lexicographically.

Please try this instead:

```
> [1, 2, 3, 10, 9].sort((a,b) => a-b)
[ 1, 2, 3, 9, 10 ]
```

By not having the array sorted properly with respect to number values the calculation of max isn't correct.

Thanks!

**Comment by rafipiccolo** [comment]
Thx, i pushed an update and acknowledged you on readme.
